### ISSUE TITLE
Sometimes the display does not turn on when waking from sleep

### ISSUE THREAD

**Issue by lbkNhubert** [TheAlexDev23/power-options#20]
Framework Laptop 16
AMD Ryzen 9 7940HS
Radeon 780M Graphics
6.10.10-arch1-1
gnome v47
wayland

**Comment by TheAlexDev23** [comment]
What settings do you have enabled from the Sleep and Screen tabs?

**Comment by lbkNhubert** [comment]
I'll have to reinstall and check. I have my system configured to suspend-then-hibernate. Running wayland so I could not install the xlock(whatever) that would enable some of the sleep settings. Let me reinstall, reboot, then check. Will update with that info.

**Comment by lbkNhubert** [comment]
Profile: display/sleep
Balanced: 20/30
Powersave++: 10/15

Configured in /etc/systemd/logind.conf to suspend-thehn-hibernate after 12 minutes. Gnome is set to 45 minutes so it should not trigger before the logind config.

**Comment by TheAlexDev23** [comment]
That's weird, because the sleep settings are X exclusive at the moment, so if you are in the GTK frontend they shouldn't even be available to modify. Could you provide the journalctl log for the power-options.service unit?

**Comment by lbkNhubert** [comment]
They are greyed out - those  are just the default values. I can adjust the ones for the display.

**Comment by TheAlexDev23** [comment]
By display you mean resolution/refresh rate? Or screen timeout?

**Comment by lbkNhubert** [comment]
![image](https://github.com/user-attachments/assets/60924b0f-96d6-4de8-ba20-e8cb1019f68b)

**Comment by TheAlexDev23** [comment]
I didn't know xset was available for wayland too. Given that you mentioned that this does not happen in ppd, I'm investigating on what they are doing differently. I do think it is something related to acpi platform profiles as you said in discord.

**Comment by lbkNhubert** [comment]
Anything that I can help to debug, I will be happy to. I am running your code now, rather than ppd. Will see if the screen doesn't come back again. The value in /sys/firmware/acpi/platform_profile does _not_ seem to be changing when running your code and changing profiles. It definitely does when running ppd. Thanks!

**Comment by TheAlexDev23** [comment]
Yeah, I haven't merged into main the code that actually changes platform_profile, because there still hasn't been any signficant testing on its stability by users with different hardware. If you're running power-options with ppd uninstalled and the same issue persists could you say what value is platform_profile? And then replicate the same but with ppd and see if ppd changes the profile on suspend enter/exit?

**Comment by TheAlexDev23** [comment]
For future readers, this was likely related with wayland and the lack of support for xset which power-options uses for screen timeout. If you are using wayland and are faced with the same issue configure the screen timeout within power-options to never and use the built in settings your os.

I'm assuming your issue got resolved since I didn't get an answer back from you. Reopen again if that isn't the case.

**Comment by lbkNhubert** [comment]
Apologies, it is intermittent and may be due to an amdgpu issue rather than anything with power-options. I am back to using it and it has been working well. The non-gtk front end causes the daemon to get into an odd state requiring a reboot to fix. I have not yet opened an issue for that. Thank you for your effort!
