### ISSUE TITLE
systemd free version?

### ISSUE THREAD

**Issue by omnigenous** [TheAlexDev23/power-options#3]
I'm on Artix linux with dinit. Is there a way to run this without systemd?

```
(1/1) reinstalling power-options-daemon                                     [-------------------------------------------] 100%
/tmp/alpm_0yOG76/.INSTALL: line 8: systemctl: command not found
/tmp/alpm_0yOG76/.INSTALL: line 9: systemctl: command not found
/tmp/alpm_0yOG76/.INSTALL: line 10: systemctl: command not found
error: command failed to execute correctly
```

**Comment by TheAlexDev23** [comment]
The daemon itself is a systemd service. It also has some DBus configuration done through systemd. So out of the box, there isn't any simple hacks to get it to run on dinit. I have zero experience with systemd alternatives, but if anyone does, in order to add support for them, you'll probably will need to change the systemd file-generating functions in:
- https://github.com/TheAlexDev23/power-options/blob/main/crates/power-daemon-mgr/src/main.rs#L319
- https://github.com/TheAlexDev23/power-options/blob/main/crates/power-daemon-mgr/src/main.rs#L348

As well as add support for non-systemctl command line utilities in:
- https://github.com/TheAlexDev23/power-options/blob/main/scripts/install-daemon.sh
- https://github.com/TheAlexDev23/power-options/blob/main/scripts/install-gtk.sh
- https://github.com/TheAlexDev23/power-options/blob/main/scripts/install-webview.sh
- https://github.com/TheAlexDev23/power-options/blob/main/scripts/uninstall.sh
- https://github.com/TheAlexDev23/power-options/blob/main/crates/power-daemon-mgr/dev-tmp-install-clean.sh
- https://github.com/TheAlexDev23/power-options/blob/main/crates/power-daemon-mgr/dev-tmp-install.sh

This should be all the parts that depend on systemd if I'm not mistaken.
